SimpleLogIn/Models/EmailModel.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;

namespace SimpleLogIn.Models
{
    
    public class EmailModel
    {
        [Key]
        public int Id { get; set; }
        
       
        public string? FullName { get; set; }
        
         
        public  string? UserEmail { get; set; }
        public string? Password { get; set; }
        [ValidateNever]
        public string? ImageUrl { get; set; }

       

    }
}

SimpleLogIn/Models/EmailModelView.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;

namespace SimpleLogIn.Models
{
    public class EmailModelView
    {
        
        public EmailModel EmailModel { get; set; }
    }
}

SimpleLogIn/Models/ErrorViewModel.cs
namespace SimpleLogIn.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SimpleLogIn/Controllers/EmailModelController.cs
using Microsoft.AspNetCore.Mvc;
using SimpleLogIn.Data;
using SimpleLogIn.Models;
using System.Drawing.Imaging;
using Microsoft.AspNetCore.Session;
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.VisualBasic;
using Microsoft.Win32;
using System.Diagnostics.Metrics;
using System.Net.Mail;
using System.Net;
using System.Reflection.Metadata;
using SimpleLogIn.Repository.IRepository;

namespace SimpleLogIn.Controllers
{
    public class EmailModelController : Controller
    {

        private readonly IEmailModelRepository _emailrepository;
        private readonly IWebHostEnvironment _WebHostEnvironment;
        public EmailModelController(IEmailModelRepository dbContext, IWebHostEnvironment webHostEnvironment)
        {
            _emailrepository = dbContext;
            _WebHostEnvironment = webHostEnvironment;

        }

        public IActionResult Index()
        {

            List<EmailModel> emailList = _emailrepository.GetAllUser().ToList();
            return View(emailList);
        }

       
        public IActionResult Create()
        {
            EmailModelView vm = new()
            {
                EmailModel = new EmailModel()
            };
            return View();
        }

        [HttpPost]
       
        public IActionResult Create(EmailModelView obj, IFormFile imageUrl)
        {
            if (ModelState.IsValid)
            {
               
                var check = _emailrepository.GetAUser(u=>u.FullName == obj.EmailModel.FullName || u.UserEmail== obj.EmailModel.UserEmail);
                if (check != null) 
                {
                    TempData["error"] = "Email already exist";
                    return View(obj);
                }
                else
                {
                    string wwwRootPath = _WebHostEnvironment.WebRootPath;

                    if (imageUrl != null && IsImageFile(imageUrl.FileName))
                    {
                       string fileName = Guid.NewGuid().ToString() + Path.GetExtension(imageUrl.FileName);//naming the files and its extension.


                       string productPath = Path.Combine(wwwRootPath, @"Images\Photos"); //location to save file 


                       using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                       {
                            imageUrl.CopyTo(fileStream);
                       }

                             
                       obj.EmailModel.ImageUrl= @"\Images\Photos\" + fileName;
                    }

                    try
                    {


                        _emailrepository.AddAUser(obj.EmailModel);
                       SendEmailNotification(obj);
                        _emailrepository.Save();

                        return RedirectToAction("Index");

                    }
                    catch (Exception)
                    {

                        TempData["error"] = "Invalid file format.Please enter a valid image file!";
                    }
                }
            }

            

            return View();
        }


        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
         public IActionResult Login(EmailModel objEmailModel) 
         {
            if (ModelState.IsValid)
            {
                var user = _emailrepository.GetAUser(u => u.FullName == objEmailModel.FullName && u.UserEmail == objEmailModel.UserEmail && u.Password == objEmailModel.Password);  
                
                if(user != null)
                {
                    

                    HttpContext.Session.SetString("FullName", user.FullName);
                    HttpContext.Session.SetString("UserEmail", user.UserEmail);
                    HttpContext.Session.SetString("password", user.Password);
                    HttpContext.Session.SetString("ImageUrl", user.ImageUrl);
                   

                    return RedirectToAction("Dashboard");
                }

                else
                {
                    
                    TempData["error"] = "Invalid Credentials";
                    return View(objEmailModel);
                }
            }

            return RedirectToAction("Index");
         }

        public IActionResult Dashboard()
        {
        
          ViewBag.FullName = HttpContext.Session.GetString("FullName");
            ViewBag.ImageUrl = HttpContext.Session.GetString("ImageUrl");

            return View();
        }

        public IActionResult Logout()
        {

            HttpContext.Session.Remove("FullName");

            return RedirectToAction("Index");
        }


        [NonAction]
        private bool IsImageFile(string fileName)
        {
                bool isValid = false;
                string[] fileExtensions = { ".bmp", ".jpg", ".png", ".gif", ".jpeg", ".BMP", ".JPG", ".PNG", ".GIF", ".JPEG" };

           for (int i = 0; i < fileExtensions.Length; i++)
           {
                 if (fileName.Contains(fileExtensions[i]))
                 {
                     isValid = true;
                 }
           }
              return isValid;  
        }


        private void SendEmailNotification(EmailModelView user)
        {
            try
            {
                // Set up the SMTP client with your email server details
                using (SmtpClient smtpClient = new SmtpClient("smtp.gmail.com"))
                {
                    smtpClient.Port = 587;
                    smtpClient.Credentials = new NetworkCredential("kadwales@gmail.com", "iokioioii");
                    smtpClient.EnableSsl = true; // Use SSL if required

                    // Create the email message
                    MailMessage mailMessage = new MailMessage();
                    mailMessage.From = new MailAddress("kadwales@gmail.com");
                    mailMessage.To.Add(user.EmailModel.UserEmail); // Replace with the new user's email
                    mailMessage.Subject = "Welcome to my simple login Website";
                    mailMessage.Body = "Dear " + user.EmailModel.FullName + ",\n\nWelcome to our website!";

                    // Send the email
                    smtpClient.Send(mailMessage);
                }
            }
            catch (Exception)
            {
                //this is not necessary because if the user's email doesnt exist the smtp provider will send an error message to that effect
                TempData["errorEmail"] = "Email doe not exist";
            }
        }
    }
    
}

SimpleLogIn/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SimpleLogIn.Models;
using System.Diagnostics;

namespace SimpleLogIn.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SimpleLogIn/Views/EmailModel/Create.cshtml
@model EmailModelView
<h1>@ViewBag.msg</h1>

<form  method="post" enctype="multipart/form-data">
    @*<input asp-for="Id" hidden />*@
    <input asp-for="EmailModel.ImageUrl" hidden />
    <div class="row">
        <div class="col-6  mx-auto card card-body">

            <div class="mt-4 mb-3">
                <input asp-for="@Model.EmailModel.FullName" placeholder="Name" type="text" />
                <label asp-for="@Model.EmailModel.FullName"> Full Name</label>
               
            </div>

            <div class="mt-4 mb-3">
                <input asp-for="@Model.EmailModel.UserEmail" placeholder="Name" type="email" />
                <label asp-for="@Model.EmailModel.UserEmail"> User Email</label>
                <span>@TempData["errorEmail"]</span>
            </div>
            <div class="mb-3">
                <input placeholder="Password" asp-for="@Model.EmailModel.Password" />
                <label asp-for="@Model.EmailModel.Password"> Password</label>
                
            </div>

            <div class=" mb-3 row p-1">
                <label asp-for="@Model.EmailModel.ImageUrl" class="ms-2"></label>
                <input type="file" name="imageUrl" id="imageUrl" class="form-control border-0 shadow" />
                
            </div>
            <span class="text-warning"> @TempData["error"]</span>
        </div>
    </div>

    <div class="row">
        <div class="col-6 col-md-3">
            <button type="submit" class="btn btn-primary  mt-4 form-control">Sign Up</button>
        </div>
    </div>


</form>

SimpleLogIn/Views/EmailModel/Dashboard.cshtml
@model EmailModel
<h1>Dash Board</h1>


<div>

   
    <h1>Welcome @ViewBag.FullName </h1>
    <div class="rounded-pill">
        <img src="@ViewBag.ImageUrl" width = "30%"/>
    </div>
    <p>This is your dashboard.</p>

    <a asp-controller="EmailModel" asp-action="Logout">Log Out</a>
</div>

SimpleLogIn/Views/EmailModel/Index.cshtml
@model List<EmailModel>

<div class="container">
    <div class="row pt-4 pb-4">
        <div class=" col-6">
            <h2 class="text-primary">
                User List
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="EmailModel" asp-action="Create" class="btn btn-primary">
                SignUp 
            </a>

            <a asp-controller="EmailModel" asp-action="Login" class="btn btn-primary">
                LogIn
            </a>

        </div>
    </div>
   <table class="table table-bordered table-striped" style="width: 100%">
        <thead>
            <tr>

                <th>Full Name</th>
                <th>Email</th>
                <th>Password</th>
                <th>Image Url</th>

            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>@item.FullName</td>
                    <td>@item.UserEmail</td>
                    <td>  @item.Password</td>
                    <td>  @item.ImageUrl</td>
                </tr>
            }

    </tbody>
    </table>
</div>

SimpleLogIn/Views/EmailModel/Login.cshtml
@model EmailModel

<form method="post">
    <div class="row">
        <div class="col-6  mx-auto card card-body">

            <div class="mt-4 mb-3">
                <input asp-for="FullName" placeholder="Name" type="text" />
                <label asp-for="FullName"> Full Name</label>
                <span asp-validation-for="FullName"></span>
            </div>

            <div class="mt-4 mb-3">
                <input asp-for="UserEmail" placeholder="Email" type="email" />
                <label asp-for="UserEmail"> User Email</label>
                <span asp-validation-for="UserEmail"></span>
            </div>
            <div class="mb-3">
                <input placeholder="Password" type="password" asp-for="Password" />
                <label asp-for="Password"> Password</label>
                <span asp-validation-for="Password"></span>
            </div>

            <h2>@TempData["error"]</h2>

        </div>
    </div>

    <div class="row">
        <div class="col-6 col-md-3">
            <button type="submit" class="btn btn-primary  mt-4 form-control" asp-controller="EmailModel" asp-action="Login" >Login</button>
        </div>
    </div>
</form>

SimpleLogIn/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SimpleLogIn/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleLogIn</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SimpleLogIn.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SimpleLogIn</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="EmailModel" asp-action="Index">SignUp/Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SimpleLogIn - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>